import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-neground dark:bg-neground">

        <div 
          className="pointer-events-none fixed top-[-20%] left-[-20%] w-screen h-[100vw] md:w-[50vw] md:h-[50vw] z-0 opacity-15"
          style={{
            background: 'radial-gradient(circle, #C48B55 0%, transparent 70%)'
          }}
          aria-hidden="true" 
        />
        
        <div 
          className="pointer-events-none fixed bottom-[-20%] right-[-20%] w-[120vw] h-[120vw] md:w-[50vw] md:h-[50vw] z-1 opacity-15"
          style={{
            background: 'radial-gradient(circle, #C48B55 0%, transparent 70%)'
          }}
          aria-hidden="true" 
        />

        {children}
      </body>
    </html>
  );
}
